package com.github.standobyte.jojo.api.rollback;

/**
 * Stable machine-readable reason for a rollback readiness or commit outcome.
 */
public enum RollbackReason {
	NONE,
	FEATURE_UNAVAILABLE,
	NOT_SERVER_THREAD,
	SERVER_UNAVAILABLE,
	UNKNOWN_HANDLE,
	OWNER_MISMATCH,
	DIMENSION_MISMATCH,
	SERVER_EPOCH_MISMATCH,
	SCOPE_OUT_OF_BOUNDS,
	INVALIDATED,
	EXPIRED,
	ACTIVE_TRANSACTION_LIMIT,
	POLICY_LIMIT_EXCEEDED,
	CHUNK_NOT_LOADED,
	CHUNK_UNLOADED,
	INSUFFICIENT_HISTORY,
	UNSUPPORTED_CAPABILITY,
	ADAPTER_CONFLICT,
	SERIALIZED_BYTES_LIMIT,
	CAPTURE_TIME_LIMIT,
	TICKS_BACK_OUT_OF_RANGE,
	APPLY_FAILED,
	INVERSE_REPLAY_FAILED
}
